In [1]:
import numpy as np

In [3]:
np.array([1,2,3,4,5]) # tạo numpy array từ python list

array([1, 2, 3, 4, 5])

In [4]:
np.array([1,2,3,4,5], dtype='float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [6]:
a1 = np.array([1, 2, 3, 4])

In [7]:
type(a1)

numpy.ndarray

In [8]:
a2 = np.array([[1,2,3],
               [4,5,6]])

In [9]:
type(a2)

numpy.ndarray

In [10]:
a2.shape

(2, 3)

In [11]:
a2.ndim #số chiều của mảng

2

In [12]:
a2.dtype # tìm kiêủ dữ liệu bên trong array

dtype('int64')

In [13]:
a2.size

6

## Creating Numpy Array from Scratch
# zeros, ones, full, arange, linspace

In [18]:
np.zeros([2,4], dtype='int') # tạo dữ liệu là kiểu cho trước và tự điền vào số 0

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
np.ones((3,5),dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
np.full((3,5), 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [23]:
np.linspace(0,1,5) # chia khoảng cách

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### random

In [26]:
np.random.random((4,4))

array([[0.52018284, 0.62664331, 0.10928973, 0.04057619],
       [0.18182957, 0.05706428, 0.56191055, 0.81303008],
       [0.3342588 , 0.28941518, 0.61240867, 0.83294508],
       [0.69363197, 0.29549851, 0.08116072, 0.92980849]])

In [31]:
np.random.rand(4,4)

array([[0.79374608, 0.61144698, 0.5177382 , 0.1630505 ],
       [0.9983069 , 0.41398441, 0.64190371, 0.69896444],
       [0.77046169, 0.52600926, 0.00400592, 0.71790991],
       [0.20334761, 0.90990572, 0.78022186, 0.2146235 ]])

### Seed trong random

In [29]:
np.random.seed()
np.random.random((4,4))

array([[0.2818969 , 0.24021984, 0.22566992, 0.13976141],
       [0.50160886, 0.36148508, 0.2024927 , 0.56164292],
       [0.62574629, 0.96818405, 0.01580157, 0.54840129],
       [0.82958944, 0.29331078, 0.18103386, 0.12388113]])

In [30]:
np.random.randint(0,10,(4,5))

array([[5, 3, 5, 7, 4],
       [9, 6, 9, 0, 2],
       [6, 0, 0, 0, 3],
       [5, 4, 9, 7, 6]], dtype=int32)

## Array Indexing & slicing

In [40]:
x1 = np.random.randint(20, size= 6)

In [41]:
x1

array([ 7, 17, 12,  0, 10, 15], dtype=int32)

In [42]:
x1[4], x1[0], x1[-1]

(np.int32(10), np.int32(7), np.int32(15))

In [43]:
x2 = np.random.randint(10, size = (3,4))

In [44]:
x2

array([[1, 5, 5, 0],
       [3, 7, 7, 7],
       [6, 2, 1, 9]], dtype=int32)

In [48]:
x2[2,3] = 5

In [49]:
x2

array([[1, 5, 5, 0],
       [3, 7, 7, 7],
       [6, 2, 1, 5]], dtype=int32)

### Slicing

In [50]:
x1

array([ 7, 17, 12,  0, 10, 15], dtype=int32)

In [53]:
x1 [3:5]

array([ 0, 10], dtype=int32)

In [54]:
x1[::-1]

array([15, 10,  0, 12, 17,  7], dtype=int32)

In [55]:
x2

array([[1, 5, 5, 0],
       [3, 7, 7, 7],
       [6, 2, 1, 5]], dtype=int32)

In [58]:
x2[0:2,0:3]

array([[1, 5, 5],
       [3, 7, 7]], dtype=int32)

### Reshaping of Array & Transpose

In [61]:
grid = np.arange(1,10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
x = np.array([1,2,3])
x.shape

(3,)

In [63]:
x.reshape((1,3))

array([[1, 2, 3]])

In [64]:
x = np.array([[1,2],[3,4]])

In [65]:
x

array([[1, 2],
       [3, 4]])

In [66]:
x.transpose()

array([[1, 3],
       [2, 4]])

### Array Concatenation and Splitting

In [67]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [71]:
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [72]:
grid = np.array([[1,2,3],
                 [4,5,6]])

In [76]:
np.concatenate((grid,grid),axis=1) # nối theo cột

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [77]:
np.concatenate((grid,grid)) # nối theo dòng

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [78]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                 [4,5,6]])
np.vstack((x,grid)) # nối khác kích thước theo dòng

array([[1, 2, 3],
       [9, 8, 7],
       [4, 5, 6]])

In [82]:
y = np.array([[2],[2]])
grid = np.array([[9,8,7],
                 [4,5,6]])
np.hstack((y,grid)) # nối khác kích thước theo cột

array([[2, 9, 8, 7],
       [2, 4, 5, 6]])

### Splitting of arrays

In [85]:
x= np.array([1,2,3,4,55,6,7,7,1])


In [87]:
np.split(x,[3,5])

[array([1, 2, 3]), array([ 4, 55]), array([6, 7, 7, 1])]

In [ ]:
##

### Broadcasting and Vectorized operations

In [88]:
a = np.array([1,2,3])

In [89]:
a

array([1, 2, 3])

In [90]:
a +5

array([6, 7, 8])

### Manipulating anh Comparing Arrays

In [91]:
list_numbers = [1,2,3]
ll= np.array(list_numbers)

In [92]:
sum(ll)

np.int64(6)

In [93]:
np.sum(ll)

np.int64(6)

In [98]:
massive_array = np.random.random(1000000)

In [99]:
massive_array.size

1000000

In [100]:
massive_array.shape

(1000000,)

In [104]:
%timeit sum(massive_array)

65.6 ms ± 2.62 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [106]:
%timeit np.sum(massive_array)

422 μs ± 9.37 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [107]:
np.mean(massive_array)

np.float64(0.5000302673309941)

In [108]:
np.max(massive_array)

np.float64(0.9999995942612702)

# Sorting Arrays (sử dụng Quick Sort)

In [109]:
x = np.array([0,3,4,5,21,1,2])

In [110]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5, 21])

In [112]:
np.argsort(x) # hàm trà về vị trí (index) của dãy đã sắp xếp

array([0, 5, 6, 1, 2, 3, 4])

### Sorting along rows and columns

In [113]:
np.random.seed(42)
MatA = np.random.randint(0,10, size=(4,6))

In [114]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

In [117]:
np.sort(MatA, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]], dtype=int32)

### Linear Algebra (đại số tuyến tính)

In [118]:
np.random.seed(0)
sales_amounts = np.random.randint(0,20, size=(5,3))

In [119]:
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [121]:
import pandas as pd
weekly_sales = pd.DataFrame(sales_amounts, index=['Mon','Tue','Wed','Thurs','Fri'], columns = ['Almond Butter',' Peanut Butter', 'Cashew Butter'])

In [122]:
weekly_sales

Almond Butter   Peanut Butter  Cashew Butter
Mon               12              15              0
Tue                3               3              7
Wed                9              19             18
Thurs              4               6             12
Fri                1               6              7

In [123]:
# Giá của butter
prices = np.array([10,8,12])

In [125]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index=['Price'], columns = ['Almond Butter',' Peanut Butter', 'Cashew Butter'])

In [126]:
butter_prices

Almond Butter   Peanut Butter  Cashew Butter
Price             10               8             12

In [127]:
total_prices = weekly_sales.dot(butter_prices.transpose())

In [128]:
total_prices

Price
Mon      240
Tue      138
Wed      458
Thurs    232
Fri      142

In [129]:
weekly_sales['Total_prices']=total_prices

In [130]:
weekly_sales

Almond Butter   Peanut Butter  Cashew Butter  Total_prices
Mon               12              15              0           240
Tue                3               3              7           138
Wed                9              19             18           458
Thurs              4               6             12           232
Fri                1               6              7           142