In [52]:
import numpy as np

In [53]:
np.array([1,2,3], dtype='float32')

array([1., 2., 3.], dtype=float32)

In [54]:
# tạo một array có 20 phần tử thuộc đoạn [1,100] cách đều nhau và cho biết khoảng cách giữa 2 phần tử là bao nhiêu
np.linspace(start=1, stop=100, num=20, endpoint=True, retstep=True)
# endpoint=True: lấy điểm cuối
# retstep=True: thể hiện khoảng cách giữa các điểm

(array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
         21.84210526,  27.05263158,  32.26315789,  37.47368421,
         42.68421053,  47.89473684,  53.10526316,  58.31578947,
         63.52631579,  68.73684211,  73.94736842,  79.15789474,
         84.36842105,  89.57894737,  94.78947368, 100.        ]),
 np.float64(5.2105263157894735))

In [55]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [56]:
arr = np.array([[1,2,3],[4,5,6]])
np.save('D:\\array.npy',arr)

In [57]:
np.load('D:\\array.npy')

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
np.random.permutation(4) #

array([3, 2, 0, 1], dtype=int32)

In [59]:
# tạp mảng 1 chiều gồm 20 số nguyên nhận các giá trị 101, 102,... 120 in a
a = np.arange(101,121,1,int)
a

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119, 120])

In [60]:
# Tạo mảng 1 chiều b gồm 50 số nguyên nhận các giá trị ngẫu nhiên trong đoạn [-10000,10000]
b = np.random.randint(-10000,10000,size=50)
b

array([-8559, -2255,  1121, -8368, -3862, -4467,  8803, -3596,   939,
       -5715,  3511,  -313,  7150, -7289,  5127, -1263,   836, -7070,
         163,  1575,  1433,  1758, -8677, -3043,  -949, -4823,  5006,
         495, -8586, -8918,  6786,  1379,  7011,  4555, -5211,  9484,
       -9293,  6252,  7579, -1149,  1865, -1293, -1310,  9826, -6325,
        9703,  1454, -8281,  8567,  6088], dtype=int32)

In [61]:
# tạo mảng c chứa các số dương của b
c = b[b>0]
c

array([1121, 8803,  939, 3511, 7150, 5127,  836,  163, 1575, 1433, 1758,
       5006,  495, 6786, 1379, 7011, 4555, 9484, 6252, 7579, 1865, 9826,
       9703, 1454, 8567, 6088], dtype=int32)

In [62]:
# tạo mảng d chứa các số đối của b
d = -b
d

array([ 8559,  2255, -1121,  8368,  3862,  4467, -8803,  3596,  -939,
        5715, -3511,   313, -7150,  7289, -5127,  1263,  -836,  7070,
        -163, -1575, -1433, -1758,  8677,  3043,   949,  4823, -5006,
        -495,  8586,  8918, -6786, -1379, -7011, -4555,  5211, -9484,
        9293, -6252, -7579,  1149, -1865,  1293,  1310, -9826,  6325,
       -9703, -1454,  8281, -8567, -6088], dtype=int32)

In [63]:
# tìm vị trí của phần tử nhỏ nhất trên b
for i in range(0,len(b)):
    if b[i] == b.min():
        print(i)

36


In [64]:
# Tạp mảng e chứa các phần tử của b nằm ở các vị trí được chỉ định trên mảng f (ví dụ f[1,4,6])
e = b[np.array([1,4,6])]
e

array([-2255, -3862,  8803], dtype=int32)

In [65]:
b

array([-8559, -2255,  1121, -8368, -3862, -4467,  8803, -3596,   939,
       -5715,  3511,  -313,  7150, -7289,  5127, -1263,   836, -7070,
         163,  1575,  1433,  1758, -8677, -3043,  -949, -4823,  5006,
         495, -8586, -8918,  6786,  1379,  7011,  4555, -5211,  9484,
       -9293,  6252,  7579, -1149,  1865, -1293, -1310,  9826, -6325,
        9703,  1454, -8281,  8567,  6088], dtype=int32)

In [66]:
# tìm median của dãy b
np.median(b)

np.float64(329.0)

In [67]:
# tạo mảng 2 chiều T kích thức 3 x 4 gồm các số ngẫu nhiên trong đoạn [-100,100]. In T và các tham số cơ bản của T
T = np.random.randint(-100,200, size=12).reshape(3,4)
T

array([[-71,  27, -98, 190],
       [129, -14,   4,  60],
       [-44, -15, 152, -20]], dtype=int32)

In [74]:
# tìm vị trí của phnâầ tuưử nhoỏ nhất trên mỗi dòng của T
 np.argmin(T,axis=1)

IndentationError: unexpected indent (2794672629.py, line 2)

In [ ]:
np.unravel_index(T, k.shape)

In [ ]:
# tìm vị trí của phần tử lớn nhất trên mỗi dòng của T