In [1]:
import numpy as np

In [9]:
np.arange(5,10,2, float)

array([5., 7., 9.])

In [14]:
np.linspace(5,20,num=6,retstep=True, axis=0)

(array([ 5.,  8., 11., 14., 17., 20.]), np.float64(3.0))

In [15]:
np.indices((3,4),dtype=int)

array([[[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]])

In [16]:
x = np.arange(20).reshape(5,4)

In [17]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [18]:
row, col = np.indices((3,4))

In [19]:
row

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

In [20]:
x[row,col]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])