## Hồi quy đa thức

In [3]:
import pandas as pd
path = 'https://raw.githubusercontent.com/datasethub/ds105/master/Model_Dataset_Lab.csv'
df = pd.read_csv(path)

In [4]:
X = df['highway-mpg']
y =df['price']

In [5]:
import numpy as np

In [8]:
p = np.polyfit(X,y,3) # biên đôi

In [9]:
m = np.poly1d(p)

In [10]:
print(m)

        3         2
-1.665 x + 216.1 x - 9335 x + 1.416e+05


In [11]:
## Hồi quy đa thức nhiều biến

## Hồi quy đa thức nhiều biến

In [15]:
# Bước 1: Biến đổi các biến ( 2 biến bậc 2 thành 5 biến bậc 1)
from sklearn.preprocessing import PolynomialFeatures

In [16]:
p = PolynomialFeatures(degree=2, include_bias=False)

In [19]:
f = p.fit_transform(df[['horsepower','curb-weight']])

In [21]:
df[['horsepower','curb-weight']].head(1)

horsepower  curb-weight
0        68.0         1967

In [23]:
f[0] # đã được chuyển đổi sang dạng 5 biến

array([6.800000e+01, 1.967000e+03, 4.624000e+03, 1.337560e+05,
       3.869089e+06])

In [26]:
# Bước 2: xây dựng mô hình với hồi qyu tuyến tính đa biến
from sklearn.linear_model import LinearRegression
m5 = LinearRegression()
m5.fit(f,y)

LinearRegression()

In [27]:
m5.predict(p.fit_transform([[68,1967]]))

array([6701.86409469])

In [28]:
### Phương pháp 3 bước (có bổ sung thêm bước chuẩn hoá dữ lệu trước khi chạy bước 1 và 2

In [29]:
# Bước 1: CHuẩn hoá dữ liêu
from sklearn.preprocessing import StandardScaler

In [31]:
SS = StandardScaler()
df_SS = SS.fit_transform(df[['horsepower','curb-weight']]) #dữ liê đã được chuẩn hoá

In [32]:
from sklearn.preprocessing import PolynomialFeatures
p2 = PolynomialFeatures(degree=2, include_bias=False)
f2 = p.fit_transform(df_SS)

In [34]:
from sklearn.linear_model import LinearRegression
m6 = LinearRegression()
m6.fit(f2,y)

LinearRegression()

In [36]:
m6.predict((p2.fit_transform([[111,2548]])))

array([9.31256871e+09])

In [38]:
m6.predict(f2)

array([ 6701.8640947 , 14777.45192303, 13296.24559464,  9674.32154569,
        6865.59516561, 20816.00995274, 10030.63578156,  6655.84309117,
        7417.9396747 ,  7327.62689192,  6872.51931087, 18314.74780039,
       35338.24767076, 17164.64851998,  9930.67225139,  5627.45451485,
       10412.15788885, 18623.45827539,  6701.8640947 ,  9123.44295738,
       23785.02556756,  6754.39420493,  9935.04562817, 13039.3833531 ,
       29124.60656475, 18992.01861062, 15536.37774707,  6677.88260376,
        8589.42113536, 14437.35349616, 32128.22922324,  6275.87004538,
        5915.69922251, 13389.98717919, 16244.9190886 ,  7316.59313274,
        7246.88339314,  9469.50119048, 15574.99984172,  6645.67599125,
        5999.75976826, 18312.40576616, 10463.47236371,  8835.00355525,
       21469.47557443, 10034.44920801, 30081.44919785,  8604.81509489,
        6637.75209971,  6682.8580016 , 17748.66814322,  6801.62085164,
        6750.69427278, 20156.83837822, 16943.62125231,  7133.06867489,
      

## Kỹ thuật pineline

In [7]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [62]:
Z= df[['horsepower','curb-weight','engine-size','highway-mpg']]
Input = [
    ('scale', StandardScaler()),
    ('polynomial', PolynomialFeatures(degree=3,include_bias=False)),
    ('model', LinearRegression())
]

In [63]:
pipe = Pipeline(Input)
pipe

Pipeline(steps=[('scale', StandardScaler()),
                ('polynomial',
                 PolynomialFeatures(degree=3, include_bias=False)),
                ('model', LinearRegression())])

In [64]:
pipe.fit(Z,y)

Pipeline(steps=[('scale', StandardScaler()),
                ('polynomial',
                 PolynomialFeatures(degree=3, include_bias=False)),
                ('model', LinearRegression())])

In [65]:
Z.head(1)

horsepower  curb-weight  engine-size  highway-mpg
0        68.0         1967           90           38

In [66]:
pipe.predict([[68,1967,90,38]])

C:\Users\phatlt17420\PycharmProjects\Python_BA\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([6892.58299907])

### Thang đo MSE

In [16]:
# Bước 1: Biến đổi các biến ( 2 biến bậc 2 thành 5 biến bậc 1)
from sklearn.preprocessing import PolynomialFeatures
y = df['price']
X3 = df[['horsepower', 'curb-weight']]
p3 = PolynomialFeatures(degree=3, include_bias=False)
f3 = p3.fit_transform(X3)
df[['horsepower', 'curb-weight']].head(1)

from sklearn.linear_model import LinearRegression

m9 = LinearRegression()
m9.fit(f3, y)

LinearRegression()

In [10]:
from sklearn.metrics import mean_squared_error, r2_score

In [17]:
y_hat_m9 = m9.predict(f3)

In [80]:
mean_squared_error(y, y_hat_m9)

10088151.010271646

In [8]:
from sklearn.preprocessing import PolynomialFeatures
y = df['price']
X4 = df[['horsepower', 'curb-weight']]
p = PolynomialFeatures(degree=4, include_bias=False)
f4 = p.fit_transform(X4)
df[['horsepower', 'curb-weight']].head(1)

from sklearn.linear_model import LinearRegression

m10 = LinearRegression()
m10.fit(f4, y)
y_hat_m10 = m10.predict(f4)

In [11]:
mean_squared_error(y, y_hat_m10)

9456365.59906096

In [14]:
m10.score(f4,y)

0.8514583041484153

In [18]:
m9.score(f3,y)

0.8415341450819717